GET https://localhost:4300/api/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmY3YTYxNC1lYWEyLTRjNmYtMTJhNC0wOGRjZjBhYTMzZWUiLCJlbWFpbCI6InBlZHJpbmhvQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoicGVkcmluaG8iLCJnaXZlbl9uYW1lIjoicGVkcmluaG8iLCJuYmYiOjE3Mjk4Mjg1MDIsImV4cCI6MTczMDI2MDUwMiwiaWF0IjoxNzI5ODI4NTAyLCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.1qFnazLVAfNGRnLcvZu8zrKHsskMBeDvJCC3_AiEkfE
